import { Providers } from '@/shared/config/providers'
import './global.css'

export const metadata = {
  title: 'Welcome to host',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">     
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  )
}
