import { Providers } from "@/shared/config/providers";
import { cn } from "@/shared/lib/utils";
import { Open_Sans } from "next/font/google";

import "./global.css";

const poppins = Open_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Welcome to host",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(poppins.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
