import { FullScreenContainer } from "@/shared/ui/fullscreen-container";

export const metadata = {
  title: "Welcome to host",
  description: "Generated by create-nx-workspace",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FullScreenContainer className="flex items-center justify-center py-10 px-5">
      {children}
    </FullScreenContainer>
  );
}
