import { AuthPagesLayout } from "@/widgets/auth-pages-layout/auth-pages-layout";

export const metadata = {
  title: "Welcome to host",
  description: "Generated by create-nx-workspace",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AuthPagesLayout>{children}</AuthPagesLayout>;
}
